FROM amd64/amazoncorretto:17
WORKDIR /app
COPY ./build/libs/backend-0.0.1-SNAPSHOT.jar /app/LOST-NO-MORE.jar
CMD ["java", "-Duser.timezone=Asia/Seoul", "-jar", "-Dspring.profiles.active=dev", "LOST-NO-MORE.jar"]