spring:
  profiles:
    default: local
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    root: INFO
    com.yourpackage: DEBUG
    web: DEBUG